services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_distribuido
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-python:
    build: ./api-python
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend-springboot:  # <--- esta línea tenía un espacio de más
    build: ./frontend-springboot
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      api-python:
        condition: service_started
